# Generated by Django 3.0.1 on 2020-01-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200104_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items_json',
            new_name='itemsJson',
        ),
    ]
